AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: Reddit Subtopic Cache

Resources:
  GetRedditCache:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.yajac.reddit.lambda.RedditCacheReadHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
  SetRedditCache:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.yajac.reddit.lambda.RedditCacheWriteHandler
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]

#  PostHelloWorld:
#    Type: AWS::Serverless::Function
#    Properties:
#      Handler: org.yajac.reddit.cache.handler.RedditCacheHandlerr
#      Runtime: java8
#      Role:
#        Fn::ImportValue:
#          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
#      Events:
#        PostEvent:
#          Type: Api
#          Properties:
#            Path: /
#            Method: post
